

services:
  fml_postgres:
    image: postgres:16
    container_name: fml_postgres
    volumes:
      - ~/.pg/pg_data/fml:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mlbb_faceit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fm_docker
    depends_on:
      - fml_postgres
      - redis
    volumes:
      - static_volume:/fm/static
      - media_volume:/fm/media
      - daphne_socket:/tmp
    env_file:
      - .env
    command: >
      bash -c "python manage.py collectstatic --noinput && python manage.py migrate && daphne -u /tmp/daphne.sock mlbb_faceit.asgi:application"

  nginx:
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    container_name: fm_nginx
    volumes:
      - static_volume:/fm/static
      - media_volume:/fm/media
      - daphne_socket:/tmp
    depends_on:
      - mlbb_faceit
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
  
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: >
      celery -A mlbb_faceit.celery worker --loglevel=info
    depends_on:
      - redis
      - fml_postgres

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: >
      celery -A mlbb_faceit.celery beat --loglevel=info
    depends_on:
      - redis
      - fml_postgres

volumes:
  static_volume:
  media_volume:
  daphne_socket:
